# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/noahliucn/MyNesEmulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/noahliucn/MyNesEmulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/noahliucn/MyNesEmulator/CMakeFiles /Users/noahliucn/MyNesEmulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/noahliucn/MyNesEmulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CPU_Test

# Build rule for target.
CPU_Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CPU_Test
.PHONY : CPU_Test

# fast build rule for target.
CPU_Test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPU_Test.dir/build.make CMakeFiles/CPU_Test.dir/build
.PHONY : CPU_Test/fast

#=============================================================================
# Target rules for targets named MyNesEmulator

# Build rule for target.
MyNesEmulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyNesEmulator
.PHONY : MyNesEmulator

# fast build rule for target.
MyNesEmulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNesEmulator.dir/build.make CMakeFiles/MyNesEmulator.dir/build
.PHONY : MyNesEmulator/fast

Bus.o: Bus.cpp.o
.PHONY : Bus.o

# target to build an object file
Bus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPU_Test.dir/build.make CMakeFiles/CPU_Test.dir/Bus.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNesEmulator.dir/build.make CMakeFiles/MyNesEmulator.dir/Bus.cpp.o
.PHONY : Bus.cpp.o

Bus.i: Bus.cpp.i
.PHONY : Bus.i

# target to preprocess a source file
Bus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPU_Test.dir/build.make CMakeFiles/CPU_Test.dir/Bus.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNesEmulator.dir/build.make CMakeFiles/MyNesEmulator.dir/Bus.cpp.i
.PHONY : Bus.cpp.i

Bus.s: Bus.cpp.s
.PHONY : Bus.s

# target to generate assembly for a file
Bus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPU_Test.dir/build.make CMakeFiles/CPU_Test.dir/Bus.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNesEmulator.dir/build.make CMakeFiles/MyNesEmulator.dir/Bus.cpp.s
.PHONY : Bus.cpp.s

CPU.o: CPU.cpp.o
.PHONY : CPU.o

# target to build an object file
CPU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPU_Test.dir/build.make CMakeFiles/CPU_Test.dir/CPU.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNesEmulator.dir/build.make CMakeFiles/MyNesEmulator.dir/CPU.cpp.o
.PHONY : CPU.cpp.o

CPU.i: CPU.cpp.i
.PHONY : CPU.i

# target to preprocess a source file
CPU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPU_Test.dir/build.make CMakeFiles/CPU_Test.dir/CPU.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNesEmulator.dir/build.make CMakeFiles/MyNesEmulator.dir/CPU.cpp.i
.PHONY : CPU.cpp.i

CPU.s: CPU.cpp.s
.PHONY : CPU.s

# target to generate assembly for a file
CPU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPU_Test.dir/build.make CMakeFiles/CPU_Test.dir/CPU.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNesEmulator.dir/build.make CMakeFiles/MyNesEmulator.dir/CPU.cpp.s
.PHONY : CPU.cpp.s

cpu_test.o: cpu_test.cpp.o
.PHONY : cpu_test.o

# target to build an object file
cpu_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPU_Test.dir/build.make CMakeFiles/CPU_Test.dir/cpu_test.cpp.o
.PHONY : cpu_test.cpp.o

cpu_test.i: cpu_test.cpp.i
.PHONY : cpu_test.i

# target to preprocess a source file
cpu_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPU_Test.dir/build.make CMakeFiles/CPU_Test.dir/cpu_test.cpp.i
.PHONY : cpu_test.cpp.i

cpu_test.s: cpu_test.cpp.s
.PHONY : cpu_test.s

# target to generate assembly for a file
cpu_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPU_Test.dir/build.make CMakeFiles/CPU_Test.dir/cpu_test.cpp.s
.PHONY : cpu_test.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNesEmulator.dir/build.make CMakeFiles/MyNesEmulator.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNesEmulator.dir/build.make CMakeFiles/MyNesEmulator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNesEmulator.dir/build.make CMakeFiles/MyNesEmulator.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CPU_Test"
	@echo "... MyNesEmulator"
	@echo "... Bus.o"
	@echo "... Bus.i"
	@echo "... Bus.s"
	@echo "... CPU.o"
	@echo "... CPU.i"
	@echo "... CPU.s"
	@echo "... cpu_test.o"
	@echo "... cpu_test.i"
	@echo "... cpu_test.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

